### PR TITLE
Use meta JSON for deno.land/x and deno.land/std

### LINKED ISSUE #24: Use meta versions
e.g. https://cdn.deno.land/deno/meta/versions.json

(rather than gross rate-limitable hack...)

### PR DESCRIPTION
**Pull request by rclarey**
Closes #24 

@hayd

### CODE REVIEW

**Comment by shah** [comment]
I was curious when this will be "released" as part of a new version. Any updates planned?

**Comment by hayd** [comment]
@shah released as 0.4.0.

**Comment by hayd** [comment]
@rclarey I've seen you've posted a bunch here so I've added you as a collaborator to udd: you can merge PRs and create releases. 😎  Thanks!!

**Comment by shah** [comment]
Thanks @hayd! Is there a specific way we should upgrade or just delete the existing version and then run `deno install -A -f -n udd https://deno.land/x/udd/main.ts`?

**Comment by hayd** [comment]
`deno install -A -f -n udd https://deno.land/x/udd@0.3.0/main.ts`

should do the trick

**Pull request merged**
