### PR TITLE
Feat: Add support for pax.deno.dev

### PR DESCRIPTION
**Pull request by 4513ECHO**
https://github.com/kawarimidoll/pax.deno.dev
https://pax.deno.dev

### CODE REVIEW

**Comment by hayd** [comment]
thanks, sure!

please can you run deno fmt on the code? seems like the tests fail because of this :)

**Comment by 4513ECHO** [comment]
Hi @hayd, Thanks for review.
I formated code by `deno fmt`. Could you review?

**Comment by 4513ECHO** [comment]
@hayd Is there anything that is not enough for this PR? I'm waiting merge for 3 months...

**Comment by hayd** [comment]
just slipped past - apologies, all looks good, will be in next release.

**Comment by 4513ECHO** [comment]
Thanks a lot!

**Pull request merged**
